Tgp 1045/implement withdraw advice endpoint
hmrc/trader-goods-profiles pull request #110
Opened 2024-07-11 15:41 UTC by omotrium

2024-07-11 16:08 UTC, william-eyre commented on it/test/uk/gov/hmrc/tradergoodsprofiles/controllers/WithdrawAdviceControllerIntegrationSpec.scala
> +    stubRouterResponse(NO_CONTENT, routerResponse.toString)
This is simpler, then you can get rid of the declaration at the top as well. 
```suggestion
    stubRouterResponse(NO_CONTENT, "204")
```

2024-07-11 16:11 UTC, william-eyre commented on test/uk/gov/hmrc/tradergoodsprofiles/controllers/WithdrawAdviceControllerSpec.scala
> +    "return 204" in {
You can remove this test, the httpStatus is being tested again in the test below

2024-07-11 16:14 UTC, william-eyre requested changes

2024-07-11 16:14 UTC, william-eyre commented on it/test/uk/gov/hmrc/tradergoodsprofiles/controllers/WithdrawAdviceControllerIntegrationSpec.scala
> +    stubRouterResponse(NO_CONTENT, routerResponse.toString)
This can be replaced, you can then delete the variable at the top. 
```suggestion
    stubRouterResponse(NO_CONTENT, "204")
```

2024-07-11 16:14 UTC, william-eyre commented on test/uk/gov/hmrc/tradergoodsprofiles/controllers/WithdrawAdviceControllerSpec.scala
> +    "return 204" in {
You can remove this test, the httpStatus is being tested again in the test below

2024-07-16 08:24 UTC, william-eyre approved these changes

2024-07-18 10:10 UTC, IoannisLazaridis-oc approved these changes

2024-07-18 14:18 UTC, merged