TGP-1889: remove client ID from the header of get Record. category in…
hmrc/trader-goods-profiles pull request #114
Opened 2024-07-23 10:06 UTC by mauro-fanton

… EIS response is optional now

2024-07-23 13:48 UTC, IoannisLazaridis-oc approved these changes

2024-07-23 13:51 UTC, IoannisLazaridis-oc requested changes
Sicne we changed the category - now we need to update the `app/uk/gov/hmrc/tradergoodsprofiles/templates/ApiSchema.scala.txt`

2024-07-23 13:54 UTC, IoannisLazaridis-oc requested changes
Should we include more test cases with category as optional in payload?

2024-07-23 14:06 UTC, mauro-fanton commented
HI @IoannisLazaridis-oc what kind of test are you think about, because we are probably already testing that and that may be implementation details. But we can have a talk if you want to see if these test add any value.

2024-07-24 07:55 UTC, IoannisLazaridis-oc approved these changes

2024-07-24 11:52 UTC, merged